### ISSUE TITLE
Add pre-commit hooks

### ISSUE THREAD

**Issue by alysivji** [alysivji/busy-beaver#23]
https://github.com/pre-commit/pre-commit/

At the moment, we are linting with `flake8` in CI but not enforcing it thru GitHub pre-commit hooks. My IDE auto-formats code with `Black`, but we do not run the format check in Travis.

Using pre-commit hooks will make it easier to enforce linting with `flake8` and code formatting with `black`.

The black Readme has [instructions on how to set this up](https://github.com/ambv/black#version-control-integration).

Definition of done includes updating instructions and adding the [black repo badge](https://camo.githubusercontent.com/28a51fe3a2c05048d8ca8ecd039d6b1619037326/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f636f64652532307374796c652d626c61636b2d3030303030302e737667) in the project `README.md`.

**Comment by thejessleigh** [comment]
I'm happy to take a look at this! Probably won't make much progress until the weekend since my week is looking super busy. LMK if that timeline works for you :)

**Comment by alysivji** [comment]
Works for me! I updated the initial post with a few more details.

Ping me if you have any questions. Thanks for your help!

**Comment by alysivji** [comment]
@thejessleigh Wanted to check in to see if you are still interested in working on this issue. Take your time, no rush. Just a friendly ping! :D

**Comment by thejessleigh** [comment]
Ah shoot. Time totally got away from me. I'd definitely still like to take a look. Sorry about that!

**Comment by alysivji** [comment]
Closed by #92
