### ISSUE TITLE
Clarify instructions for setting up local development environment

### ISSUE THREAD

**Issue by alysivji** [alysivji/busy-beaver#44]
This is still not obvious.

**Comment by oikake** [comment]
damn straight it's not :stuck_out_tongue:

**Comment by alysivji** [comment]
Ha! Give me a week and I'll get everything sorted. I'm on vacation starting Friday.

**Comment by uncojohnco** [comment]
I started a fork of the install docs [here](https://github.com/uncojohnco/busy-beaver/wiki/Install). Will update this sandbox as I go through the install process

**Comment by uncojohnco** [comment]
Let us know @alysivji when you have had a chance to do an iteration of the docs and have decoupled the credentials of external services from development. I can then do a review as I've hit a roadblock on #72. Upon scouting the issue, it would require effort on my part to troubleshoot atm...?

related #72

**Comment by uncojohnco** [comment]
Forgot to add fork of the docs, thought I would play around with the wiki feature...
https://github.com/uncojohnco/busy-beaver/wiki

**Comment by alysivji** [comment]
Flask migration is done, I just need to add some tests, clean up, and deploy. Next, I will start working on cleaning up contributor docs. Lots of learnings will be in there. Wednesday at the lastest.

Off to a coffee shop to work all day.
