### ISSUE TITLE
[Query] sudo require for `make build` command

### ISSUE THREAD

**Issue by oikake** [alysivji/busy-beaver#67]
Is it expected to run the `make build` command in sudo?  

https://github.com/alysivji/busy-beaver/blob/e59de95a54978b1fdc6304b220e90ab980d7f65d/Makefile#L31-L32

This is on Ubuntu 16.10
Linux 4.18.0

**Comment by alysivji** [comment]
I don't have to on my mac or the ubuntu 18.04 LTS server, this might be how you have your docker installation set up.

Not sure.

**Comment by oikake** [comment]
Looks like it was a user permissions issue...

https://docs.docker.com/install/linux/linux-postinstall/
> The Docker daemon binds to a Unix socket instead of a TCP port. By default that Unix socket is owned by the user root and other users can only access it using sudo. The Docker daemon always runs as the root user.
> 
> If you don’t want to preface the docker command with sudo, create a Unix group called docker and add users to it. When the Docker daemon starts, it creates a Unix socket accessible by members of the docker group.

https://techoverflow.net/2017/03/01/solving-docker-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket/
https://docs.docker.com/install/linux/linux-postinstall/

sudo not required now ^_^
