### ISSUE TITLE
enable git-lfs

### ISSUE THREAD

**Issue by uncojohnco** [alysivji/busy-beaver#87]
@alysivji - could you enable [git-lfs](https://help.github.com/en/articles/configuring-git-large-file-storage) for the repo and merge the changes into master?
```
git lfs install
git lfs track "*.png"
```

Also, do you have any pref for where to store images, assets, etc pertaining to the docs?

**Comment by uncojohnco** [comment]
Also, note that LFS needs to be enabled from the original repo in-order for forked repos to push LFS objects :( 
https://github.com/git-lfs/git-lfs/issues/1449

**Comment by alysivji** [comment]
Let me read up on LFS, it's been a year since I last used it. Want to make sure I do it correctly.

My pragmatic side says that we have ~ 300kb of images. Lot bigger fish to fry imo.
